### ISSUE TITLE
Running tests in Circle CI's docker container 

### ISSUE THREAD

**Issue by aamorozov** [blueimp/nightwatch#10]
Hi @blueimp! Thank you for a great tool! I have a question regarding using this project in continuous integration, in my case Circle CI. Have you used it in the CI environment? I'm struggling a bit in either I should keep using docker compose or just rely on CI's default docker image? Please advice if you have the context on it. 
Thank you!

**Comment by blueimp** [comment]
Hi @aamorozov 
I'm not a Circle CI user, but this project requires multiple Docker images and not a single one.

The nightwatch Docker image only contains the nightwatch executable, but you will still need at least the Chromedriver one as well as the Docker images containing your own application code.

If your CI system supports it, you would use docker compose.

**Comment by aamorozov** [comment]
@blueimp Thank you! It does support multiple images, I'll discover further by myself
