### ISSUE TITLE
Getting exception while using these libraries 

### ISSUE THREAD

**Issue by bhajojo** [blueimp/nightwatch#4]
I am getting exception while running the docker compose command for running the test from my existing night watch project 

There was an error while starting the test runner:

Error: Cannot read source folder: /home/node/examples/tests
    at /usr/lib/node_modules/nightwatch/lib/runner/run.js:200:21
    at /usr/lib/node_modules/nightwatch/lib/runner/walk.js:97:18
    at FSReqWrap.oncomplete (fs.js:82:15)

Please look into this issue

**Comment by blueimp** [comment]
Please see issue #2
