### ISSUE TITLE
Pass command-line-options to nightwatch

### ISSUE THREAD

**Issue by ximo1984** [blueimp/nightwatch#6]
Hi, 
I think that it would be useful if we could pass command line options to the nigthwatch instance. http://nightwatchjs.org/guide#command-line-options.

Thanks in advance.

**Comment by subhojit777** [comment]
You can already do it. Like this `docker-compose run --rm nightwatch --env prod`

**Comment by ximo1984** [comment]
In fact, I want to generate JUnit XML reports but when I try this it doesn't works:

docker-compose run --rm nightwatch --output reports

Thanks for your help.

**Comment by ximo1984** [comment]
I changed nightwatch.json configuration and change:
"output_folder": "reports"

And it works!!
