### ISSUE TITLE
Image that doesn't require a volume

### ISSUE THREAD

**Issue by IvanAnishchuk** [blueimp/nightwatch#7]
Is there any particular reason for mounting video recorder module as a volume instead of installing it right into the image?

**Comment by blueimp** [comment]
The volume mount is necessary anywhere for the tests.
Installing the video recorder module in there via local node_modules keeps it modular.
There are e.g. also two other related modules I've added, that people might or might not want to use:
https://github.com/blueimp/node-ffmpeg-image-diff
https://github.com/blueimp/nightwatch-browserstack
