### ISSUE TITLE
file path of entrypoint.sh not found

### ISSUE THREAD

**Issue by ravivalm** [blueimp/nightwatch#8]
hi i used the command "docker-compose run --rm nightwatch"
ERROR: Cannot start service nightwatch: oci runtime error: container_linux.go:265: starting container process caused "exec: \"entrypoint\": executable file not found in $PATH"

**Comment by blueimp** [comment]
Can you reproduce the problem if you do the following:

```sh
git clone https://github.com/blueimp/nightwatch.git
cd nightwatch
docker-compose run --rm nightwatch
```

The entrypoint executable is definitely part of the nightwatch docker image, as it's added here:
https://github.com/blueimp/nightwatch/blob/master/Dockerfile#L34

**Comment by blueimp** [comment]
Closing as non-reproducible.
